baseurl: /mall_doc
permalink: /:year/:month/:day/:title.html
date: "YYYY-MM-DD HH:MM:SS"
defaults:
  -
    scope:
      path: "" # 空表示所有文件
    values:
      layout: "post"
      author: "findever"
      category: "未分类"
